encoding: utf-8
permalink: pretty

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

url: https://maxkrasnov.ru
enforce_ssl: maxkrasnov.ru

sass:
  style: compressed
languages: ['ru', 'en']
defaultLang: ru
defaults:
  - scope:
      path: ''
    values:
      lang: 'ru'
      layout: 'default'
  - scope:
      path: 'en'
    values:
      lang: 'en'

gems:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 10
paginate_path: "/:num"
