encoding: utf-8
permalink: pretty
highlighter: rouge
sass:
  style: compressed
languages: ['ru', 'en']
defaultLang: ru
defaults:
  - scope:
      path: ''
    values:
      lang: 'ru'
      layout: 'default'
  - scope:
      path: 'en'
    values:
      lang: 'en'

gems:
  - jekyll-paginate
  - jekyll-redirect-from

paginate: 10
paginate_path: "/:num"
